title: Mi laboratorio SOC
description: Tutoriales de detección de ataques, malware y análisis forense
theme: jekyll-theme-hacker
markdown: kramdown

author:
  name: CypherHero92
  avatar: /assets/images/Cypher2.jpg
  Instagram: https://instagram.com/CypherHero92
  X: https://twitter.com/CypherHero92
  Github: https://github.com/CypherHero92
  AlienVault: https://otx.alienvault.com/user/CypherHero92
  
